mlkv_plus:
  gpu_init_capacity: 300_000
  gpu_max_capacity:  300_000
  hbm_gb: 5
  gpu_ids: [0]
  enable_gds_log: false
  enable_gds_get_from_sst: true
  disableWAL: false
  rocksdb_path: ./mlkv_plus_rocksdb
  force_skip_memtable: false
  rocksdb_use_direct_reads: true


hkv:
  gpu_init_capacity: 1_000_000
  gpu_max_capacity: 10_000_000
  hbm_gb: 1
  gpu_ids: [0]


DistMLKVPlusBinding:
  gpu_init_capacity: 900000
  gpu_max_capacity: 900000
  hbm_gb: 5


rocksdb:
  rocksdb_path: /tmp/rocksdb_ycsb_db
  create_if_missing: true
  disableWAL: true
  gpu_ids: 0